name: Release all mobile packages

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-mobile-packages:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if tagged push to main
        id: check_tag
        run: |
          echo "::set-output name=tagged_push::false"
          if [[ "${{ github.ref }}" == "refs/heads/main" && ! -z "${{ github.event.push.tags }}" ]]; then
            echo "::set-output name=tagged_push::true"
            echo "Branch is main and tag is present"
          else
            echo "Branch is not main or tag did not trigger workflow"
          fi

      - name: Get the tag name
        if: steps.check_tag.outputs.tagged_push == 'true'
        id: tag_name
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

      - name: Git configuration
        if: steps.check_tag.outputs.tagged_push == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
