name: Release all mobile packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-mobile-packages:
    runs-on: macOS-latest
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release ${{ env.TAG_NAME }}'
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
